### PR TITLE
Update chinese translation

### PR DESCRIPTION
**Pull request by yoshimo0417**

### CODE REVIEW

**Comment by Argent77** [comment]
Thank you for the translation!

Could you also provide me with the translation of the following words?
- Cardinal directions: `east`, `southeast`, `southwest`, `west`, `northwest`, `northeast`
- The string: `RUBIKON GRID` (used for "RUBIKON GRID 1-1", "RUBIKON GRID 1-2", ...)

I can use them to create translated versions of compass markers and room labels.

**Comment by MephistoSatanDevil** [comment]
> Thank you for the translation!
> 
> Could you also provide me with the translation of the following words?
> 
> * Cardinal directions: `east`, `southeast`, `southwest`, `west`, `northwest`, `northeast`
> * The string: `RUBIKON GRID` (used for "RUBIKON GRID 1-1", "RUBIKON GRID 1-2", ...)
> 
> I can use them to create translated versions of compass markers and room labels.

`east` : `东`
`southeast` : `东南`
`southwest` : `西南`
`west` : `西`
`northwest` : `西北`
`northeast` : `东北`
`north` : `北`
`south` : `南`

`RUBIKON GRID` : `卢比刚网格`

**Comment by yoshimo0417** [comment]
Thanks for the reply. Please use the translation provided by @MephistoSatanDevil for those words.

**Comment by Argent77** [comment]
Added. Thank you!

**Pull request merged**
